# ---
# - name: Configure Web Server
#   hosts: webservers
#   become: yes
#   vars:
#     package_name: nginx
#     service_name: nginx
#   tasks:
#     - name: Install Web Server
#       apt:
#         name: "{{ package_name }}"
#         state: present
#         update_cache: yes

#     - name: Start Web Server
#       service:
#         name: "{{ service_name }}"
#         state: started
#         enabled: yes

#     # - name: Check Nginx Status
#     #     hosts: webservers
#     #     become: yes  # This is equivalent to the -b flag
   
#     - name: Check Nginx service status
#         shell: systemctl status nginx
#         register: nginx_status

#     - name: Print Nginx status
#       ping:

#     - name: Print Nginx status
#       debug:
#         var: nginx_status.stdout


---
- name: Configure Web Server
  hosts: webservers
  become: yes
  vars:
    package_name: nginx
    service_name: nginx
  tasks:
    - name: Install Web Server
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes

    - name: Start Web Server
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: Check Nginx service status
      shell: systemctl status nginx
      register: nginx_status

    - name: Print Nginx status
      debug:
        var: nginx_status.stdout
