#!/mnt/c/Users/MaxwellAdomako/ansible/project-1/ansi-env/bin/ansible-playbook
- name: Introduction Ansible Playbook
  hosts: backend
  remote_user: ubuntu
  # hosts: backend
  become: 'yes'
  become_user: root

  vars: 
    test: "hello, this is a test"
    my_name: "Maxwell Adomako"
    my_age: 25
    my_height: 5.8
    gender: "male"

  tasks:
    - name: Reading Ansible Playbook Variables
      debug:
        var: test
    - name: Reading Ansible Playbook Variables
      debug:    
        msg: >
          - My Name is: {{ my_name }}
          - My Age is: {{ my_age }}
          - My Height is: {{ my_height }}
          - I am a: {{ gender }}

