# # 

# # NEW FIX FOR VAGRANT 2.2.6
# Vagrant.configure("2") do |config|
#   config.vm.provider "virtualbox" do |vb|
#     vb.memory = "3024"
#     vb.cpus = 2
#   end

#   config.vm.define "web" do |web|
#     web.vm.box = "ubuntu/focal64"
#     web.vm.hostname = "web"
#     web.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
#   end

#   config.vm.define "db" do |db|
#     db.vm.box = "ubuntu/focal64"
#     db.vm.hostname = "db"
#     db.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  
#   end
# end


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3024"
    vb.cpus = 2
  end

  config.vm.define "site" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "site"
    web.vm.network "public_network", ip: "192.168.1.10", bridge: "en0: Wi-Fi (AirPort)"
  end

  config.vm.define "base" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "base"
    db.vm.network "public_network", ip: "192.168.1.11", bridge: "en0: Wi-Fi (AirPort)"
  end
end
