# 

# NEW FIX FOR VAGRANT 2.2.6
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3024"
    vb.cpus = 2
  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web"
    web.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

    # web.vm.provision "shell", inline: <<-SHELL
    #   sudo apt-get update
    #   sudo apt-get install -y apache2
    # SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db"
    db.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

    # ansible.vm.provision "shell", inline: <<-SHELL
    #   sudo apt-get update
    #   sudo apt-get install -y python3
    # SHELL
  end
end
