---
# tasks file for webservers

#  tasks file for webservers
# - name: Install Web Server
#   apt:
#     name: "{{ package_name }}"
#     state: present
#     update_cache: yes

# - name: Start Web Server
#   service:
#     name: "{{ service_name }}"
#     state: started
#     enabled: yes


- name: Install Web Server
  apt:
    name: "{{ package_name }}"
    state: present
    update_cache: yes

- name: Start Web Server
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: Deploy custom Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: A simple html Project Using Ansible
  template:
    src: index.html
    dest: /var/www/html/index.html
  # notify: Restart Nginx

