---
# tasks file for webservers

#  tasks file for webservers
- name: Install Web Server
  apt:
    name: "{{ package_name }}"
    state: present
    update_cache: yes

- name: Start Web Server
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes